name: Lint *.include JSON

on:
  push:
    paths:
      - "boilerplate-v1/**/*.include"
      - ".github/workflows/lint-includes.yml"
      - ".github/workflows/lint/lint-includes.py"
  pull_request:
    paths:
      - "boilerplate-v1/**/*.include"
      - ".github/workflows/lint-includes.yml"
      - ".github/workflows/lint/lint-includes.py"
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Lint *.include JSON
      run: python .github/workflows/lint/lint-includes.py
